---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: magnonellie/amethyst-dependencies
    tag: stable

inputs:
- name: amethyst

run:
  path: sh
  dir: amethyst
  args:
  - -exc
  - cargo fmt --all -- --check
