---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: magnonellie/amethyst-dependencies
    tag: stable

inputs:
- name: amethyst
- name: target

run:
  path: sh
  dir: amethyst
  args:
  - -exc
  - mdbook test book -L ../target/debug/deps
